export interface LearnTopic {
  slug: string;
  title: string;
  category: 'Содержание' | 'Организация' | 'Язык' | 'Произношение';
  taskLabels: string[];
  lead: string;
  keyPoints: string[];
  goodExamples: string[];
  badExamples?: string[];
  examTip: string;
  practicePrompt: string;
}

export const LEARN_TOPICS: Record<string, LearnTopic> = {
  'direct-question-word-order': {
    slug: 'direct-question-word-order',
    title: 'Прямые вопросы в английском',
    category: 'Язык',
    taskLabels: ['Задание 2'],
    lead: 'В задании 2 засчитываются именно прямые вопросы. В них вспомогательный глагол, модальный глагол или be обычно стоит перед подлежащим.',
    keyPoints: [
      'Для be: Where is the clinic? / Are there any discounts?',
      'Для обычных смысловых глаголов: Do you offer family discounts?',
      'Для can/could: How can I get there? / Can I book online?',
      'Не начинайте вопрос с утверждения: The clinic is where?',
    ],
    goodExamples: [
      'Where is your clinic located?',
      'How can I get to the clinic by public transport?',
      'Do you offer family discounts?',
    ],
    badExamples: [
      'Where your clinic is located?',
      'How I can get to the clinic?',
      'You offer family discounts?',
    ],
    examTip: 'Перед записью быстро выберите шаблон: Where is...? / How can I...? / Do you...? / Is there...?',
    practicePrompt: 'Составьте 4 прямых вопроса к рекламе: location, price, opening hours, discounts.',
  },
  'auxiliary-verbs-questions': {
    slug: 'auxiliary-verbs-questions',
    title: 'Do/does/did и be в вопросах',
    category: 'Язык',
    taskLabels: ['Задание 2'],
    lead: 'В английском вопросе часто нужен вспомогательный глагол. Без него вопрос звучит как утверждение или как ошибка порядка слов.',
    keyPoints: [
      'Используйте do/does для Present Simple: Do you have...? / Does the centre offer...?',
      'Используйте did для Past Simple: Did the course start last week?',
      'Если в предложении есть be, do не нужен: Is the school near the station?',
      'Если есть can, will, should, они идут перед подлежащим: Can I pay online?',
    ],
    goodExamples: [
      'Do you have classes in the evening?',
      'Is the swimming pool open at weekends?',
      'Can I get there by bus?',
    ],
    badExamples: [
      'You have classes in the evening?',
      'Does the swimming pool is open?',
      'How I can get there?',
    ],
    examTip: 'Если сомневаетесь, начните с Do you...? — это безопасный шаблон для многих пунктов рекламы.',
    practicePrompt: 'Переделайте утверждения в прямые вопросы: You have discounts. The centre is open on Sundays. I can book online.',
  },
  'there-is-are': {
    slug: 'there-is-are',
    title: 'There is / there are',
    category: 'Язык',
    taskLabels: ['Задание 2', 'Задание 3', 'Задание 4'],
    lead: 'There is / there are помогает говорить о наличии чего-либо. В вопросе порядок меняется: Is there...? / Are there...?',
    keyPoints: [
      'There is + единственное число: Is there a café near the hotel?',
      'There are + множественное число: Are there any discounts for students?',
      'В вопросах с any: Are there any extra classes?',
      'Не смешивайте there is и множественное число.',
    ],
    goodExamples: [
      'Is there a bus stop near the clinic?',
      'Are there any family discounts?',
      'There are two people in the first photo.',
    ],
    badExamples: [
      'Are there a bus stop?',
      'Is there any discounts?',
      'There is two people in the photo.',
    ],
    examTip: 'После there сразу проверьте число существительного: one thing → is, several things → are.',
    practicePrompt: 'Составьте 5 вопросов с Is there...? / Are there...? по теме school facilities.',
  },
  'transport-questions': {
    slug: 'transport-questions',
    title: 'Как спрашивать про транспорт',
    category: 'Язык',
    taskLabels: ['Задание 2'],
    lead: 'Пункт public transport часто проверяет не только вопрос, но и устойчивые выражения: get to, by bus, bus stop, near.',
    keyPoints: [
      'Самый универсальный вопрос: How can I get there by public transport?',
      'Можно спросить о ближайшей остановке: Is there a bus stop near your centre?',
      'Не говорите on public transport в таком контексте; обычно by public transport.',
      'Если место известно, используйте get to the clinic / get there.',
    ],
    goodExamples: [
      'How can I get to your centre by public transport?',
      'Is there an underground station near the school?',
      'Which bus should I take to get there?',
    ],
    badExamples: [
      'How can I go on public transport?',
      'Where is transport?',
      'What public transport?',
    ],
    examTip: 'Для ЕГЭ достаточно одного ясного вопроса: How can I get there by public transport?',
    practicePrompt: 'Спросите про транспорт до museum, language school, sports centre и clinic.',
  },
  'task2-content-points': {
    slug: 'task2-content-points',
    title: 'Как раскрывать пункты задания 2',
    category: 'Содержание',
    taskLabels: ['Задание 2'],
    lead: 'Каждый вопрос должен точно соответствовать пункту задания. Если пункт price, вопрос должен быть про цену, а не про скидки или расписание.',
    keyPoints: [
      'Сначала прочитайте четыре пункта и мысленно подберите вопросительное слово.',
      'location → Where is...? / Where are you located?',
      'price → How much is...? / What is the price of...?',
      'discounts → Do you offer discounts for...?',
    ],
    goodExamples: [
      'Point: location → Where is your clinic located?',
      'Point: family discounts → Do you offer family discounts?',
      'Point: opening hours → What are your opening hours?',
    ],
    badExamples: [
      'Point: price → Are there discounts?',
      'Point: public transport → Where is your website?',
      'Point: location → Is it good?',
    ],
    examTip: 'Не усложняйте: один пункт = один прямой вопрос ровно по этому пункту.',
    practicePrompt: 'Возьмите любую рекламу и составьте по одному вопросу к пунктам: location, price, duration, discounts.',
  },
  'direct-vs-indirect-questions': {
    slug: 'direct-vs-indirect-questions',
    title: 'Прямой вопрос vs косвенный вопрос',
    category: 'Язык',
    taskLabels: ['Задание 2'],
    lead: 'В задании 2 нужен прямой вопрос. Косвенные фразы вроде Could you tell me... можно использовать, но они повышают риск ошибки порядка слов.',
    keyPoints: [
      'Прямой вопрос: Where is the clinic?',
      'Косвенный вопрос: Could you tell me where the clinic is?',
      'После Could you tell me порядок слов как в утверждении: where the clinic is, не where is the clinic.',
      'На экзамене безопаснее задавать короткие прямые вопросы.',
    ],
    goodExamples: [
      'Where is the clinic?',
      'How much does the course cost?',
      'Do you offer discounts?',
    ],
    badExamples: [
      'Could you tell me where is the clinic?',
      'I want to know how much does it cost?',
      'Tell me the price?',
    ],
    examTip: 'Если не уверены в косвенном вопросе, не используйте его. Прямой вопрос легче и надёжнее.',
    practicePrompt: 'Переделайте 5 косвенных вопросов в короткие прямые вопросы.',
  },
  'clear-questions': {
    slug: 'clear-questions',
    title: 'Как делать вопрос понятным',
    category: 'Язык',
    taskLabels: ['Задание 2'],
    lead: 'Вопрос должен быть понятным на слух: адресат должен сразу понять, какую информацию вы хотите узнать.',
    keyPoints: [
      'Называйте объект: the course, your clinic, the museum, the discount.',
      'Избегайте слишком коротких фрагментов: Price? Transport?',
      'Не задавайте два разных вопроса в одном 20-секундном ответе.',
      'Говорите спокойно, с вопросительной интонацией.',
    ],
    goodExamples: [
      'What is the price of a one-month course?',
      'Where is your language school located?',
      'Can I book a visit online?',
    ],
    badExamples: [
      'What price?',
      'Where?',
      'And transport?',
    ],
    examTip: 'Лучше короткий полный вопрос, чем длинная фраза с несколькими ошибками.',
    practicePrompt: 'Улучшите фрагменты: Price? Address? Discounts? Transport?',
  },
  'task3-full-answer': {
    slug: 'task3-full-answer',
    title: 'Как отвечать развёрнуто в задании 3',
    category: 'Содержание',
    taskLabels: ['Задание 3'],
    lead: 'В интервью нужно отвечать полно: обычно 2–3 предложения на каждый вопрос. Одно слово или короткий фрагмент не раскрывает ответ.',
    keyPoints: [
      'Первое предложение — прямой ответ на вопрос.',
      'Второе — деталь, пример или причина.',
      'Если остаётся время, добавьте короткое уточнение.',
      'Не уходите в длинный монолог: 40 секунд на один вопрос.',
    ],
    goodExamples: [
      'I live in a big city. It is quite busy, but there are many places for teenagers to go to.',
      'Yes, I enjoy reading. It helps me relax after school and learn new words.',
    ],
    badExamples: [
      'In Moscow.',
      'Yes, I do.',
      'Because it is good.',
    ],
    examTip: 'Формула: answer + detail + reason/example.',
    practicePrompt: 'Ответьте на вопрос “What do you usually do at weekends?” в 2–3 предложениях.',
  },
  'task3-two-part-questions': {
    slug: 'task3-two-part-questions',
    title: 'Двухчастные вопросы в интервью',
    category: 'Содержание',
    taskLabels: ['Задание 3'],
    lead: 'Некоторые вопросы содержат две части. Если ответить только на одну, ответ будет неполным.',
    keyPoints: [
      'Слушайте вопрос до конца: What do you like and dislike...?',
      'Отвечайте по порядку: сначала первая часть, потом вторая.',
      'Используйте маркеры: As for..., Also..., However...',
      'Если забыли вторую часть, добавьте хотя бы короткое предложение.',
    ],
    goodExamples: [
      'I like my neighbourhood because it is quiet. However, I dislike that there are not many sports facilities nearby.',
      'I live in a flat. It is small, but it is comfortable and close to my school.',
    ],
    badExamples: [
      'I like my neighbourhood because it is quiet.',
      'I live in a flat.',
    ],
    examTip: 'Когда слышите and, or, why — почти всегда нужно добавить вторую мысль.',
    practicePrompt: 'Ответьте на вопрос: What do you like and dislike about your school?',
  },
  'giving-reasons': {
    slug: 'giving-reasons',
    title: 'Как давать reason в устном ответе',
    category: 'Содержание',
    taskLabels: ['Задание 3', 'Задание 4'],
    lead: 'Если вопрос просит why или если вы выражаете мнение, нужна причина. Без неё ответ часто звучит неполно.',
    keyPoints: [
      'Используйте because, as, since для причины.',
      'Можно добавить пример: For example,...',
      'Не ограничивайтесь “because it is good” — уточните, почему именно.',
      'Причина должна быть связана с вопросом или вашим выбором.',
    ],
    goodExamples: [
      'I prefer studying in the morning because I can concentrate better.',
      'This option is better for our project because it shows how teenagers spend free time together.',
    ],
    badExamples: [
      'I like it because it is good.',
      'I choose this photo. That is all.',
    ],
    examTip: 'После каждого “I prefer / I think / I would choose” добавьте because.',
    practicePrompt: 'Закончите 5 фраз: I prefer..., because...',
  },
  'task3-relevance': {
    slug: 'task3-relevance',
    title: 'Как не уходить от темы в задании 3',
    category: 'Содержание',
    taskLabels: ['Задание 3'],
    lead: 'Ответ должен соответствовать конкретному вопросу интервьюера, а не общему топику.',
    keyPoints: [
      'Повторите ключевые слова вопроса в первом предложении.',
      'Если спросили about your neighbourhood, не говорите весь ответ about your city.',
      'Если спросили what you would like to change, назовите изменение.',
      'Не заучивайте один универсальный ответ на все вопросы темы.',
    ],
    goodExamples: [
      'I would like to change my room because it is too small for studying.',
      'I dislike the noise in my neighbourhood, especially in the evening.',
    ],
    badExamples: [
      'My city is very beautiful and many tourists visit it.',
      'I like sport and I often play football.',
    ],
    examTip: 'Первые 3–5 слов ответа должны показывать, что вы услышали именно этот вопрос.',
    practicePrompt: 'Составьте точный ответ на вопрос: What would you like to change about your flat or house?',
  },
  'task4-project-connection': {
    slug: 'task4-project-connection',
    title: 'Связь фото с проектом в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'В задании 4 вы оставляете голосовое сообщение другу о проекте. Нужно объяснить, почему фотографии подходят к теме проекта.',
    keyPoints: [
      'Назовите тему проекта в начале ответа.',
      'Скажите, что обе фотографии иллюстрируют разные стороны этой темы.',
      'Не начинайте только с “In the first photo I can see...”. Добавьте связь с проектом.',
      'Связь может быть короткой, но явной.',
    ],
    goodExamples: [
      'I think these photos are suitable for our project about ideal weekends because they show two different ways of spending free time.',
      'Both pictures can illustrate our project on healthy lifestyles, but they show different activities.',
    ],
    badExamples: [
      'In the first picture I can see people.',
      'These photos are good.',
    ],
    examTip: 'В первом или втором предложении произнесите theme of our project / our project about...',
    practicePrompt: 'Свяжите две фотографии с темой проекта “Teenagers and hobbies”.',
  },
  'task4-photo-description': {
    slug: 'task4-photo-description',
    title: 'Описание фото в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'Друг не видит фотографии, поэтому нужно кратко объяснить, что на них изображено.',
    keyPoints: [
      'Опишите обе фотографии, не только одну.',
      'Достаточно 1–2 фраз на описание.',
      'Фокусируйтесь на действиях и связи с темой, а не на мелких деталях.',
      'Не выдумывайте факты, которых нет на изображении.',
    ],
    goodExamples: [
      'The first photo shows a family having a picnic in a park. In the second photo, two teenagers are watching a film at home.',
      'One picture shows outdoor activity, while the other shows a quiet indoor activity.',
    ],
    badExamples: [
      'There are many details and colours.',
      'I can see people, and the second photo is also nice.',
    ],
    examTip: 'Формула: Photo 1 shows... Photo 2 shows...',
    practicePrompt: 'Опишите две фотографии за 2 предложения: one outdoor activity, one indoor activity.',
  },
  'task4-meaningful-difference': {
    slug: 'task4-meaningful-difference',
    title: 'Как сравнивать фотографии в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'Отличие должно быть значимым для темы проекта. Цвет одежды или количество деревьев обычно не раскрывают пункт сравнения.',
    keyPoints: [
      'Сравнивайте способ действия, место, участников или эффект.',
      'Используйте whereas / while / unlike / in contrast.',
      'Свяжите отличие с темой проекта.',
      'Не перечисляйте случайные визуальные детали.',
    ],
    goodExamples: [
      'The main difference is that the first activity is outdoors, whereas the second one is indoors.',
      'Unlike the first photo, the second one shows a more passive way to spend free time.',
    ],
    badExamples: [
      'In the first photo people wear blue clothes, but in the second photo they do not.',
      'The first photo is lighter.',
    ],
    examTip: 'Спросите себя: “Это отличие помогает раскрыть тему проекта?” Если нет — выберите другое.',
    practicePrompt: 'Сравните two ways of spending a weekend: picnic vs watching a film.',
  },
  'task4-advantages': {
    slug: 'task4-advantages',
    title: 'Advantages в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'Нужно назвать преимущества вариантов, показанных на фото. Лучше дать 1–2 ясных преимущества, чем общий комментарий.',
    keyPoints: [
      'Используйте advantage / benefit / good thing about it is...',
      'Можно дать преимущество каждого варианта.',
      'Преимущество должно быть связано с действием на фото.',
      'Не путайте advantages с вашим личным мнением — мнение будет отдельным пунктом.',
    ],
    goodExamples: [
      'The advantage of having a picnic is that people can spend time outdoors and enjoy fresh air.',
      'Watching a film at home is convenient because it is cheap and comfortable.',
    ],
    badExamples: [
      'It is good.',
      'There are advantages.',
    ],
    examTip: 'Формула: The advantage of ... is that ...',
    practicePrompt: 'Назовите по одному преимуществу для cycling и reading at home.',
  },
  'task4-disadvantages': {
    slug: 'task4-disadvantages',
    title: 'Disadvantages в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'После преимуществ нужно назвать недостатки вариантов. Они должны быть реалистичными и связанными с фото.',
    keyPoints: [
      'Используйте disadvantage / drawback / problem.',
      'Можно назвать недостаток одного или обоих вариантов.',
      'Не повторяйте advantage другими словами.',
      'Недостаток лучше объяснить одной короткой причиной.',
    ],
    goodExamples: [
      'The disadvantage of a picnic is that it depends on the weather.',
      'The drawback of watching films at home is that it can be less active and less social.',
    ],
    badExamples: [
      'It is bad.',
      'There are no disadvantages.',
    ],
    examTip: 'Если не знаете, используйте универсальные идеи: weather, cost, time, comfort, health, social contact.',
    practicePrompt: 'Назовите по одному недостатку для travelling by car и travelling by train.',
  },
  'task4-opinion': {
    slug: 'task4-opinion',
    title: 'Opinion в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'В конце нужно явно выразить своё мнение или выбор по теме проекта.',
    keyPoints: [
      'Используйте I prefer / I would choose / In my opinion.',
      'Выбор должен соответствовать формулировке задания.',
      'Не оставляйте мнение неясным: “Both are good” недостаточно.',
      'После мнения добавьте причину.',
    ],
    goodExamples: [
      'Personally, I would choose the first option because I prefer spending weekends outdoors.',
      'In my opinion, the second photo is more suitable for our project because it shows a common teenage activity.',
    ],
    badExamples: [
      'Both photos are good.',
      'That is my opinion.',
    ],
    examTip: 'Одно предложение с I would choose... уже делает мнение явным. Второе — объясняет почему.',
    practicePrompt: 'Выберите один из двух вариантов: doing sport outdoors or playing computer games at home. Объясните выбор.',
  },
  'task4-reason-for-opinion': {
    slug: 'task4-reason-for-opinion',
    title: 'Как обосновать мнение в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'Мнение без причины часто звучит неполно. Нужно объяснить, почему вы выбираете этот вариант.',
    keyPoints: [
      'Добавьте because / as / since.',
      'Причина должна быть личной или логически связанной с проектом.',
      'Можно сослаться на пользу, удобство, интерес, здоровье, общение.',
      'Не используйте пустую причину: because it is good.',
    ],
    goodExamples: [
      'I would choose the outdoor activity because it is healthier and helps people communicate more.',
      'I prefer the second option as it is cheaper and easier to organise.',
    ],
    badExamples: [
      'I choose the first photo because I like it.',
      'My opinion is the first one.',
    ],
    examTip: 'Проверка: после because можно спросить “why exactly?” — ответ должен быть конкретным.',
    practicePrompt: 'Дайте мнение и причину по теме “best way to relax after school”.',
  },
  'task4-sentence-count': {
    slug: 'task4-sentence-count',
    title: 'Объём ответа в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'Для полного ответа обычно нужно 12–15 фраз. Слишком короткий ответ почти неизбежно пропускает пункты плана.',
    keyPoints: [
      '1 фраза — приветствие и связь с проектом.',
      '2–3 фразы — описание и отличие фото.',
      '3–4 фразы — преимущества и недостатки.',
      '2–3 фразы — мнение, причина и завершение.',
    ],
    goodExamples: [
      'Hi, Alex! I’ve found two photos for our project about ideal weekends.',
      'Let me know which photo you like more for the project.',
    ],
    badExamples: [
      'In photo one people are outside. In photo two people are inside. I prefer photo one.',
    ],
    examTip: 'Не считайте каждое предложение во время ответа, но держите в голове 5 блоков плана.',
    practicePrompt: 'Составьте план из 12 коротких предложений для темы “Ideal weekend”.',
  },
  'task4-factual-mismatch': {
    slug: 'task4-factual-mismatch',
    title: 'Фактическая точность в задании 4',
    category: 'Содержание',
    taskLabels: ['Задание 4'],
    lead: 'Описание не должно противоречить фотографиям или теме проекта. Нельзя уверенно называть то, чего не видно.',
    keyPoints: [
      'Говорите только о видимых или очевидных деталях.',
      'Если не уверены, используйте looks like / seems to be.',
      'Не меняйте тему проекта на другую.',
      'Не приписывайте людям возраст, профессию или эмоции без оснований.',
    ],
    goodExamples: [
      'The people seem to be spending time in a park.',
      'The picture shows teenagers who are probably watching a film at home.',
    ],
    badExamples: [
      'They are definitely celebrating a birthday.',
      'This photo is about travelling abroad.',
    ],
    examTip: 'Если деталь не важна для темы проекта, лучше её не упоминать.',
    practicePrompt: 'Опишите фото, используя seems to be / looks like для неочевидных деталей.',
  },
  'task4-voice-message-style': {
    slug: 'task4-voice-message-style',
    title: 'Формат voice message в задании 4',
    category: 'Организация',
    taskLabels: ['Задание 4'],
    lead: 'Задание 4 — это голосовое сообщение другу, а не формальный доклад. Ответ должен звучать естественно и дружелюбно.',
    keyPoints: [
      'Начните с обращения: Hi, Alex! / Hi, Kate!',
      'Упомяните проект: I’ve found two photos for our project...',
      'Используйте естественные переходы: I think, by the way, as for me.',
      'Завершите сообщение фразой другу: Let me know what you think.',
    ],
    goodExamples: [
      'Hi, Alex! I’ve found two photos for our project about hobbies.',
      'That’s all for now. Let me know which photo you prefer.',
    ],
    badExamples: [
      'Dear examiner, I am going to compare two pictures.',
      'In conclusion, the aforementioned illustrations demonstrate...',
    ],
    examTip: 'Представьте, что реально отправляете voice message однокласснику.',
    practicePrompt: 'Запишите начало и конец voice message по теме “Healthy lifestyle”.',
  },
  'task4-closing': {
    slug: 'task4-closing',
    title: 'Заключение в задании 4',
    category: 'Организация',
    taskLabels: ['Задание 4'],
    lead: 'В конце голосового сообщения нужна короткая естественная фраза. Она закрывает ответ и сохраняет формат общения с другом.',
    keyPoints: [
      'Не заканчивайте резко сразу после мнения.',
      'Попросите друга ответить или выбрать фото.',
      'Фраза должна быть короткой и разговорной.',
      'Не используйте слишком формальное conclusion.',
    ],
    goodExamples: [
      'That’s all for now. Let me know what you think.',
      'Which photo do you like better for our project?',
      'I hope my ideas are useful. Talk to you later!',
    ],
    badExamples: [
      'That is all.',
      'In conclusion, I have finished my comparison.',
    ],
    examTip: 'Выучите 2–3 универсальные closing-фразы и используйте одну из них.',
    practicePrompt: 'Придумайте 3 завершающие фразы для voice message другу.',
  },
  'task4-linking': {
    slug: 'task4-linking',
    title: 'Связки для монолога',
    category: 'Организация',
    taskLabels: ['Задание 4'],
    lead: 'Связки помогают слушателю понять структуру: описание, отличие, преимущества, недостатки, мнение.',
    keyPoints: [
      'Для начала: First of all, I think these photos are suitable because...',
      'Для сравнения: while, whereas, unlike, in contrast.',
      'Для плюсов/минусов: The advantage is..., However, the drawback is...',
      'Для мнения: As for me, Personally, I would choose...',
    ],
    goodExamples: [
      'The first photo shows..., while the second one shows...',
      'However, this option also has a drawback.',
      'As for me, I would choose the first photo.',
    ],
    badExamples: [
      'Photo one. Photo two. Advantages. Disadvantages. I like.',
    ],
    examTip: 'Связки не должны быть сложными. Главное — чтобы план был слышен.',
    practicePrompt: 'Соедините 5 пунктов плана словами First of all, while, however, personally, finally.',
  },
  'task4-answer-plan': {
    slug: 'task4-answer-plan',
    title: 'План ответа в задании 4',
    category: 'Организация',
    taskLabels: ['Задание 4'],
    lead: 'Логичный порядок снижает риск пропустить пункт и помогает набрать баллы по организации.',
    keyPoints: [
      '1. Greeting + project topic.',
      '2. Why the photos suit the project.',
      '3. Brief description + meaningful difference.',
      '4. Advantages and disadvantages.',
      '5. Personal opinion + reason + closing.',
    ],
    goodExamples: [
      'Hi, Alex! I’ve found two photos for our project...',
      'The main difference is...',
      'Personally, I would choose...',
    ],
    badExamples: [
      'Сначала мнение, потом описание, потом снова мнение, без связи с проектом.',
    ],
    examTip: 'Во время подготовки набросайте 5 слов: project, photos, difference, pros/cons, opinion.',
    practicePrompt: 'Составьте скелет ответа по плану из 5 блоков для темы “Free time”.',
  },
  'articles-a-an': {
    slug: 'articles-a-an',
    title: 'Артикли a/an в заданиях ЕГЭ',
    category: 'Язык',
    taskLabels: ['Задание 2', 'Задание 3', 'Задание 4'],
    lead: 'Если существительное в единственном числе и его можно посчитать, обычно нужен артикль a/an или другой определитель.',
    keyPoints: [
      'a перед согласным звуком: a photo, a useful app.',
      'an перед гласным звуком: an interesting activity, an old building.',
      'Не оставляйте countable singular noun без артикля: a clinic, a discount, a person.',
      'Можно использовать the, my, this, one вместо a/an, если подходит по смыслу.',
    ],
    goodExamples: [
      'I can see an interesting photo.',
      'There is a park near my house.',
      'Do you offer a family discount?',
    ],
    badExamples: [
      'I can see interesting photo.',
      'There is park near my house.',
      'Do you offer family discount?',
    ],
    examTip: 'После каждого единственного исчисляемого существительного быстро проверьте: есть ли a/an/the/my/this?',
    practicePrompt: 'Вставьте a/an/the где нужно: interesting photo, new school, old museum, useful website.',
  },
  'plural-forms': {
    slug: 'plural-forms',
    title: 'Множественное число в устной части',
    category: 'Язык',
    taskLabels: ['Задание 2', 'Задание 3', 'Задание 4'],
    lead: 'Форма существительного должна совпадать со смыслом: один вариант или несколько, один человек или люди в целом.',
    keyPoints: [
      'many / several / different → обычно множественное число.',
      'one / a / an → единственное число.',
      'people уже множественное число: people are, не people is.',
      'discounts, classes, activities часто нужны во множественном числе.',
    ],
    goodExamples: [
      'There are many activities for teenagers.',
      'Do you offer family discounts?',
      'People are spending time outdoors.',
    ],
    badExamples: [
      'There are many activity.',
      'Do you offer family discount?',
      'People is spending time outdoors.',
    ],
    examTip: 'Слова many, different, several — сигнал проверить окончание -s.',
    practicePrompt: 'Исправьте формы: many student, different activity, two photo, people is.',
  },
  'prepositions-place': {
    slug: 'prepositions-place',
    title: 'Предлоги места',
    category: 'Язык',
    taskLabels: ['Задание 2', 'Задание 3', 'Задание 4'],
    lead: 'Предлоги места часто встречаются в описании фото, рассказе о доме/городе и вопросах про location.',
    keyPoints: [
      'in the picture/photo — на картинке/фото.',
      'in a park, in a city, in my room — внутри пространства.',
      'at school, at home, at the weekend — устойчивые выражения.',
      'near / next to / opposite — рядом, около, напротив.',
    ],
    goodExamples: [
      'In the first photo, people are sitting in a park.',
      'My school is near my house.',
      'The clinic is located in the city centre.',
    ],
    badExamples: [
      'On the first photo people are sitting.',
      'My school is on my house.',
      'The clinic is located at the city centre.',
    ],
    examTip: 'Для фото почти всегда говорите in the photo, не on the photo.',
    practicePrompt: 'Составьте 6 фраз с in the photo, in a park, at school, near my house.',
  },
  'basic-speaking-grammar': {
    slug: 'basic-speaking-grammar',
    title: 'Типичные грамматические ошибки в говорении',
    category: 'Язык',
    taskLabels: ['Задание 3', 'Задание 4'],
    lead: 'Даже при хорошей идее грубые базовые ошибки могут снизить балл за языковое оформление.',
    keyPoints: [
      'Следите за be: people are, it is, there are.',
      'В Present Simple: he/she/it + -s.',
      'Не пропускайте артикли с исчисляемыми существительными в единственном числе.',
      'Согласуйте время: прошлое событие — Past Simple, привычка — Present Simple.',
    ],
    goodExamples: [
      'People are having a picnic.',
      'My friend likes playing football.',
      'Last year I visited Saint Petersburg.',
    ],
    badExamples: [
      'People is having a picnic.',
      'My friend like playing football.',
      'Last year I visit Saint Petersburg.',
    ],
    examTip: 'Лучше простые правильные предложения, чем сложные конструкции с грубыми ошибками.',
    practicePrompt: 'Запишите 5 простых правильных предложений о своём городе и 5 — о хобби.',
  },
  'subject-verb-agreement': {
    slug: 'subject-verb-agreement',
    title: 'Subject-verb agreement',
    category: 'Язык',
    taskLabels: ['Задание 3', 'Задание 4'],
    lead: 'Подлежащее и сказуемое должны совпадать по числу и лицу: I live, he lives, people are, it is.',
    keyPoints: [
      'I/you/we/they live, like, go.',
      'he/she/it lives, likes, goes в Present Simple.',
      'people / children / teenagers are, не is.',
      'this photo is, these photos are.',
    ],
    goodExamples: [
      'This photo is suitable for our project.',
      'These photos are different.',
      'My brother likes cycling.',
    ],
    badExamples: [
      'This photo are suitable.',
      'These photos is different.',
      'My brother like cycling.',
    ],
    examTip: 'Перед глаголом быстро спросите: кто делает действие — one or many?',
    practicePrompt: 'Исправьте: people is, teenagers likes, this photos are, my friend live.',
  },
  'speaking-tenses': {
    slug: 'speaking-tenses',
    title: 'Времена в устном ответе ЕГЭ',
    category: 'Язык',
    taskLabels: ['Задание 3', 'Задание 4'],
    lead: 'Выбор времени должен соответствовать смыслу: привычки, прошлый опыт, текущая ситуация или планы.',
    keyPoints: [
      'Present Simple — привычки и общие факты: I usually spend weekends with my family.',
      'Past Simple — прошлые события: Last summer I went to the seaside.',
      'Present Continuous — то, что происходит на фото: people are playing football.',
      'Future forms — планы: I would like to live in a big city in the future.',
    ],
    goodExamples: [
      'In the photo, people are walking in a park.',
      'I usually do my homework in the evening.',
      'Last year I joined a sports club.',
    ],
    badExamples: [
      'In the photo, people walk now.',
      'Yesterday I go to school.',
      'Usually I am doing homework in the evening.',
    ],
    examTip: 'Для описания фото безопасно использовать Present Continuous: is/are + V-ing.',
    practicePrompt: 'Составьте по 3 предложения в Present Simple, Past Simple и Present Continuous.',
  },
  'speaking-vocabulary': {
    slug: 'speaking-vocabulary',
    title: 'Лексика для устной части',
    category: 'Язык',
    taskLabels: ['Задание 3', 'Задание 4'],
    lead: 'Точный выбор слов делает ответ понятным. Неестественные выражения или неверные слова могут исказить смысл.',
    keyPoints: [
      'Учите короткие устойчивые выражения: spend time, take part in, be interested in.',
      'Не переводите дословно с русского.',
      'Если забыли слово, перефразируйте проще.',
      'Для задания 4 полезны слова: advantage, drawback, suitable, compare, prefer.',
    ],
    goodExamples: [
      'spend time with friends',
      'take part in a project',
      'This photo is suitable for our project.',
    ],
    badExamples: [
      'spend time with computer games all day long time',
      'make sport',
      'do a photo for project',
    ],
    examTip: 'Говорите проще, но точнее. Простая правильная лексика лучше редких слов с ошибками.',
    practicePrompt: 'Составьте мини-словарь из 10 фраз для темы hobbies или school life.',
  },
  'clear-speaking-answer': {
    slug: 'clear-speaking-answer',
    title: 'Как сделать устный ответ понятным',
    category: 'Язык',
    taskLabels: ['Задание 3', 'Задание 4'],
    lead: 'Понятный ответ — это не набор отдельных слов, а короткие завершённые фразы с логической связью.',
    keyPoints: [
      'Говорите короткими предложениями.',
      'Заканчивайте мысль перед тем, как начинать новую.',
      'Используйте связки: and, but, because, however, as for me.',
      'Если ошиблись, не останавливайтесь надолго — переформулируйте проще.',
    ],
    goodExamples: [
      'I live in a small town. It is quiet, but there are not many places for teenagers.',
      'I prefer the first photo because it shows a healthier activity.',
    ],
    badExamples: [
      'I town small and people good because yes.',
      'Photo one good, second no, project maybe.',
    ],
    examTip: 'Темп важен: лучше медленнее и яснее, чем быстро и непонятно.',
    practicePrompt: 'Запишите 30 секунд ответа и проверьте: есть ли завершённые предложения?',
  },
};

export const LEARN_TOPIC_LIST = Object.values(LEARN_TOPICS);
